### ISSUE TITLE
create_supdoc doesn't exist in v3.0 but does in 2.1

### ISSUE THREAD

**Issue by brettkc** [Intacct/intacct_dtd#1]
Supporting documents are still a feature and referenced in v3.0 but the `create_supdoc` action is not present in 3.0 and results in API errors.

Whats the deal with this?

**Comment by jimmymcpeter** [comment]
We're actually working on getting the functions to match for next release.  Look for the changes in the coming weeks.

**Comment by brettkc** [comment]
Thanks @jimmymcpeter
